DROP TABLE IF EXISTS `users`;

CREATE TABLE `users` (
	`id`	integer	NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`user_id`	varchar(12)	UNIQUE NOT NULL,
	`password`	varchar(255)	NOT NULL,
	`name`	varchar(6)	NOT NULL,
	`email`	varchar(255)	UNIQUE NULL,
	`mobile_phone`	varchar(255)	UNIQUE NULL,
	`address`	varchar(255) NULL,
	`point`	INT UNSIGNED	NULL DEFAULT 200000
);

DROP TABLE IF EXISTS `products`;

CREATE TABLE `products` (
	`id`	integer	NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`name`	varchar(255)	NULL,
	`price`	decimal(7,0)	NULL,
	`stock`	integer	NULL	DEFAULT 99,
	`image`	varchar(255)	NULL,
	`category_id`	integer	NOT NULL
);

DROP TABLE IF EXISTS `categories`;

CREATE TABLE `categories` (
	`id`	integer	NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`name`	varchar(255)	NULL
);

ALTER TABLE `products` ADD CONSTRAINT `FK_categories_TO_products_1` FOREIGN KEY (
	`category_id`
)
REFERENCES `categories` (
	`id`
);

DROP TABLE IF EXISTS `ci_sessions`;

CREATE TABLE IF NOT EXISTS `ci_sessions` (
        `id` varchar(128) NOT NULL,
        `ip_address` varchar(45) NOT NULL,
        `timestamp` int(10) unsigned DEFAULT 0 NOT NULL,
        `data` blob NOT NULL,
        KEY `ci_sessions_timestamp` (`timestamp`)
);

-- Insert Dummy Data
INSERT INTO categories (name) VALUES ('fashion');
INSERT INTO categories (name) VALUES ('food');
INSERT INTO categories (name) VALUES ('digital');

-- fashion products
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 01', 43700, '1.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 02', 72700, '10.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 03', 73500, '1.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 04', 97400, '3.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 05', 25100, '6.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 06', 98700, '10.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 07', 53200, '7.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 08', 41300, '8.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 09', 73300, '10.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 10', 44300, '3.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 11', 97500, '7.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 12', 86300, '12.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 13', 78500, '12.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 14', 91900, '7.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 15', 64500, '9.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 16', 76300, '2.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 17', 87400, '2.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 18', 75100, '10.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 19', 39900, '11.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 20', 99700, '4.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 21', 26400, '7.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 22', 38200, '5.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 23', 43200, '11.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 24', 23500, '1.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 25', 94500, '9.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 26', 57800, '1.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 27', 82600, '8.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 28', 49900, '11.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 29', 28500, '5.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 30', 87900, '11.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 31', 14100, '7.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 32', 38700, '5.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 33', 21800, '1.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 34', 24900, '4.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 35', 58600, '6.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 36', 77400, '9.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 37', 99700, '3.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 38', 83500, '9.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 39', 69700, '6.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 40', 26400, '10.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 41', 75900, '5.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 42', 42300, '3.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 43', 79900, '10.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 44', 78900, '9.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 45', 74500, '5.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 46', 52300, '8.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 47', 63800, '2.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 48', 68600, '6.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 49', 53200, '7.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 50', 11200, '3.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 51', 24900, '9.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 52', 67600, '6.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 53', 58900, '2.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 54', 28400, '4.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 55', 67700, '10.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 56', 17900, '10.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 57', 12500, '12.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 58', 37600, '12.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 59', 33100, '2.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 60', 81400, '1.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 61', 52800, '4.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 62', 29900, '4.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 63', 52300, '11.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 64', 99600, '7.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 65', 98400, '2.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 66', 48100, '8.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 67', 33100, '7.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 68', 99100, '3.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 69', 79600, '1.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 70', 15500, '1.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 71', 26200, '7.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 72', 41300, '3.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 73', 88100, '8.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 74', 85200, '3.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 75', 25300, '4.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 76', 82700, '7.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 77', 92800, '11.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 78', 93800, '3.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 79', 18300, '11.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 80', 45800, '6.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 81', 76100, '9.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 82', 66700, '1.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 83', 62600, '12.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 84', 63900, '5.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 85', 56200, '11.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 86', 52300, '3.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 87', 88500, '11.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 88', 36600, '5.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 89', 35400, '11.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 90', 18900, '8.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 91', 27400, '6.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 92', 45900, '6.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 93', 78400, '9.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 94', 42600, '12.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 95', 66500, '10.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 96', 27900, '10.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 97', 54600, '2.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 98', 79500, '3.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 99', 71600, '9.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 100',51100, '10.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 101',69300, '8.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 102',18400, '8.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 103',11800, '8.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 104',92400, '9.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 105',87700, '8.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 106',13900, '6.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 107',67200, '10.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 108',27400, '10.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 109',47800, '2.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 110',38600, '9.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 111',34300, '2.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 112',93500, '6.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 113',29600, '8.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 114',74800, '12.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 115',55200, '2.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 116',74700, '7.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 117',76800, '8.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 118',37500, '11.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 119',74700, '4.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 120',85800, '10.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 121',12900, '6.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 122',94200, '4.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 123',91500, '6.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 124',11400, '11.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 125',86100, '11.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 126',24700, '8.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 127',27500, '4.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 128',25500, '8.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 129',72800, '2.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 130',68800, '11.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 131',19500, '5.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 132',24300, '5.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 133',86600, '9.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 134',98500, '4.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 135',22800, '1.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 136',33400, '4.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 137',74500, '1.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 138',51900, '10.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 139',51900, '8.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 140',24100, '10.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 141',57200, '6.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 142',33400, '3.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 143',97700, '5.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 144',31600, '10.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 145',59600, '6.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 146',43400, '5.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 147',49200, '9.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 148',42100, '9.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 149',43500, '2.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 150',83600, '6.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 151',77600, '7.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 152',19700, '1.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 153',13600, '12.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 154',62200, '1.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 155',42600, '1.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 156',61300, '10.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 157',58500, '7.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 158',73600, '3.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 159',55700, '7.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 160',42400, '8.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 161',35700, '4.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 162',66700, '3.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 163',56900, '12.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 164',49900, '3.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 165',15600, '11.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 166',17600, '10.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 167',27700, '6.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 168',97300, '12.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 169',75600, '2.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 170',79400, '11.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 171',32100, '9.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 172',34200, '11.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 173',14100, '2.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 174',82200, '9.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 175',59700, '8.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 176',69800, '4.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 177',11900, '6.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 178',96200, '1.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 179',17400, '12.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 180',18800, '5.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 181',96400, '3.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 182',64400, '12.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 183',49400, '11.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 184',32100, '3.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 185',57200, '11.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 186',38400, '2.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 187',91500, '4.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 188',12600, '5.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 189',56100, '10.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 190',27100, '11.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 191',15100, '8.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 192',37400, '7.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 193',69400, '10.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 194',79200, '9.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 195',95200, '9.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 196',92200, '10.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 197',47800, '4.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 198',94700, '10.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 199',89600, '4.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 200',21200, '1.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 201',77900, '6.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 202',71600, '1.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 203',55600, '1.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 204',93400, '10.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 205',57100, '8.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 206',71800, '6.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 207',26200, '4.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 208',14500, '10.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 209',27600, '2.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 210',99400, '8.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 211',25900, '4.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 212',37200, '9.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 213',27600, '7.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 214',74400, '12.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 215',41100, '4.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 216',37400, '5.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 217',31800, '6.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 218',96300, '11.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 219',87600, '2.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 220',65200, '8.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 221',53800, '12.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 222',35200, '3.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 223',71500, '3.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 224',11700, '9.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 225',74500, '8.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 226',91400, '2.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 227',93400, '12.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 228',78400, '4.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 229',77300, '5.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 230',59700, '3.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 231',25500, '7.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 232',81500, '9.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 233',78800, '3.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 234',28200, '1.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 235',74400, '8.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 236',48300, '9.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 237',89400, '2.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 238',22200, '11.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 239',25800, '11.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 240',57600, '2.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 241',59500, '8.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 242',71300, '8.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 243',89100, '3.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 244',71600, '1.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 245',78100, '11.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 246',69200, '7.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 247',56100, '3.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 248',99200, '2.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 249',87100, '12.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 250',53700, '11.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 251',18800, '6.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 252',64400, '9.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 253',59900, '5.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 254',93600, '7.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 255',49200, '4.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 256',26100, '11.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 257',78800, '4.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 258',18600, '2.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 259',68100, '10.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 260',58500, '12.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 261',84300, '5.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 262',76900, '5.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 263',84400, '10.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 264',71600, '4.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 265',79300, '4.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 266',41800, '2.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 267',42500, '6.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 268',25900, '11.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 269',57900, '5.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 270',14600, '11.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 271',15500, '5.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 272',86300, '1.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 273',17200, '7.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 274',63700, '2.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 275',86800, '9.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 276',99500, '3.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 277',82200, '6.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 278',87200, '2.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 279',33500, '11.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 280',23400, '6.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 281',75900, '2.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 282',79600, '1.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 283',59700, '8.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 284',19800, '4.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 285',91800, '7.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 286',14700, '4.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 287',95700, '8.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 288',29400, '4.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 289',31200, '5.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 290',44300, '3.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 291',41500, '3.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 292',71600, '7.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 293',23400, '11.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 294',84400, '9.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 295',42600, '4.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 296',22100, '11.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 297',52700, '8.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 298',19200, '6.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 299',32600, '8.avif', 1);
INSERT INTO products (name, price, image, category_id) VALUES ('fashion item 300',78300, '3.avif', 1);
                                                                                          
-- food products
INSERT INTO products (name, price, image, category_id) VALUES ('food item 01', 8800, '10.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 02', 2500, '1.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 03', 6300, '4.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 04', 2300, '7.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 05', 8900, '6.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 06', 7500, '7.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 07', 4800, '12.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 08', 4300, '6.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 09', 8900, '2.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 10', 1800, '1.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 11', 3600, '5.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 12', 9500, '1.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 13', 4700, '5.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 14', 8800, '6.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 15', 6900, '3.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 16', 7700, '7.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 17', 6400, '9.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 18', 5500, '7.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 19', 4800, '10.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 20', 5600, '5.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 21', 1200, '10.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 22', 2900, '3.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 23', 1900, '6.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 24', 1800, '5.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 25', 3700, '6.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 26', 5800, '9.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 27', 3900, '3.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 28', 1600, '12.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 29', 1200, '11.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 30', 2600, '8.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 31', 9900, '8.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 32', 5800, '4.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 33', 8700, '2.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 34', 2800, '3.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 35', 7700, '2.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 36', 8700, '4.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 37', 7200, '2.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 38', 2900, '12.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 39', 9600, '11.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 40', 3500, '9.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 41', 9900, '12.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 42', 6600, '7.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 43', 2200, '3.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 44', 3300, '1.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 45', 2200, '2.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 46', 3500, '12.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 47', 5500, '6.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 48', 9100, '7.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 49', 3100, '6.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 50', 6500, '2.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 51', 1500, '2.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 52', 2500, '5.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 53', 2700, '4.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 54', 6300, '5.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 55', 7300, '2.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 56', 7700, '11.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 57', 9500, '11.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 58', 5100, '12.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 59', 5900, '2.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 60', 3900, '4.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 61', 9900, '4.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 62', 2700, '10.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 63', 2800, '2.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 64', 3500, '1.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 65', 1200, '9.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 66', 3300, '4.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 67', 4900, '6.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 68', 6400, '1.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 69', 5200, '6.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 70', 4400, '9.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 71', 1500, '4.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 72', 9600, '6.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 73', 2900, '10.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 74', 3900, '11.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 75', 2400, '1.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 76', 3300, '11.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 77', 2800, '1.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 78', 8900, '3.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 79', 7100, '8.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 80', 4700, '5.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 81', 9900, '4.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 82', 7400, '8.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 83', 4200, '7.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 84', 1500, '10.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 85', 4900, '10.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 86', 4500, '10.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 87', 2400, '6.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 88', 3900, '12.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 89', 7600, '6.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 90', 1600, '12.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 91', 3700, '10.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 92', 8500, '6.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 93', 7200, '6.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 94', 3700, '10.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 95', 1700, '4.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 96', 3100, '6.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 97', 9800, '9.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 98', 3700, '4.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 99', 4500, '3.jpg', 2);
INSERT INTO products (name, price, image, category_id) VALUES ('food item 100',2500, '12.jpg', 2);

-- digital products
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 01', 38100, '4.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 02', 22700, '3.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 03', 37200, '9.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 04', 46600, '1.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 05', 67800, '8.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 06', 54200, '3.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 07', 95600, '4.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 08', 77800, '7.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 09', 63400, '3.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 10', 16600, '12.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 11', 77100, '9.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 12', 55100, '3.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 13', 63600, '11.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 14', 15400, '1.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 15', 41300, '1.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 16', 82500, '8.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 17', 98700, '5.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 18', 99800, '2.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 19', 29200, '8.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 20', 15400, '9.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 21', 85300, '5.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 22', 98400, '6.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 23', 62700, '12.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 24', 71600, '8.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 25', 53600, '7.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 26', 77200, '10.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 27', 39200, '9.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 28', 65200, '12.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 29', 67400, '9.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 30', 14500, '7.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 31', 14100, '5.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 32', 58300, '12.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 33', 75300, '6.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 34', 54200, '9.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 35', 77300, '10.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 36', 97200, '6.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 37', 29300, '3.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 38', 68500, '2.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 39', 38900, '7.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 40', 45200, '1.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 41', 76900, '8.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 42', 65400, '12.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 43', 45400, '9.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 44', 16600, '4.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 45', 93900, '2.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 46', 67900, '6.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 47', 85500, '9.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 48', 62100, '6.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 49', 41800, '1.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 50', 99600, '5.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 51', 37800, '7.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 52', 66500, '5.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 53', 16400, '10.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 54', 99500, '7.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 55', 59700, '9.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 56', 33500, '9.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 57', 33900, '7.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 58', 63300, '10.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 59', 91500, '7.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 60', 69500, '7.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 61', 53800, '10.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 62', 94200, '1.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 63', 89500, '8.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 64', 93400, '1.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 65', 33700, '8.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 66', 16300, '10.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 67', 87700, '11.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 68', 45400, '3.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 69', 44200, '8.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 70', 85100, '10.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 71', 63300, '1.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 72', 62400, '12.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 73', 11800, '12.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 74', 12800, '11.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 75', 64500, '2.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 76', 88700, '3.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 77', 55300, '1.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 78', 72400, '8.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 79', 98300, '12.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 80', 76100, '9.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 81', 98800, '7.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 82', 43700, '2.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 83', 57300, '6.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 84', 46100, '10.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 85', 41900, '6.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 86', 44900, '8.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 87', 93900, '1.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 88', 42200, '11.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 89', 23900, '2.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 90', 76600, '4.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 91', 14600, '9.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 92', 38200, '7.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 93', 12600, '6.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 94', 27300, '7.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 95', 58800, '8.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 96', 46700, '1.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 97', 75100, '11.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 98', 12500, '3.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 99', 49400, '4.jpg', 3);
INSERT INTO products (name, price, image, category_id) VALUES ('digital item 100',25800, '12.jpg', 3);